language:
  cpp
cache:
  apt:
  ccache:
  directories:
addons:
 apt:
  sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise
  packages:
    - gcc-5
    - g++-5
    - binutils
    - gawk
    - build-essential
    - wget
    - libtool
    - flex
before_script:
  - wget --no-check-certificate http://ftp.gnu.org/gnu/bison/bison-3.0.4.tar.gz
  - mkdir $HOME/bison
  - tar -xf bison-3.0.4.tar.gz; cd bison-3.0.4; ./configure --prefix=$HOME/bison; make -j 4 install; cd $PWD/..;
  - export PATH=$HOME/bison/bin:$PATH
script:
  make && make test
notifications:
  slack: qut-ifn660-javascript:L91Jp7bz9fqP8fL4gudNYu1G
